export const API_ROUTES = {
  auth: {
    validateEmail: '/api/auth/validate-email',
    login: '/api/auth/login',
    signup: '/api/auth/signup',
    checkUsername: '/api/auth/check-username',
  },
  collegeAuth: {
    login: '/api/college-auth/login',
    signup: '/api/college-auth/signup',
  },
  dashboard: {
    home: '/api/dashboard',
    profile: '/api/dashboard/profile',
    college: '/api/dashboard/college',
  },
  profile: {
    me: '/api/profile',
    byUserId: (userId) => `/api/profile/${userId}`,
    xpHistory: '/api/profile/xp-history',
    levelProgress: '/api/profile/level-progress',
    streakStatus: '/api/profile/streak-status',
    skills: '/api/profile/skills',
    stats: '/api/profile/stats',
  },
  scoring: {
    questionnaire: '/api/scoring/questionnaire',
    submit: '/api/scoring/submit',
    profile: '/api/scoring/profile',
    history: '/api/scoring/history',
    retake: '/api/scoring/retake',
  },
  leaderboard: {
    xp: '/api/leaderboard/xp',
    streak: '/api/leaderboard/streak',
    skill: (skillName) => `/api/leaderboard/skill/${encodeURIComponent(skillName)}`,
    availableSkills: '/api/leaderboard/skills/available',
    all: '/api/leaderboard/all',
    myRank: '/api/leaderboard/my-rank',
  },
  projects: {
    list: '/api/projects',
    create: '/api/projects',
    byId: (projectId) => `/api/projects/${projectId}`,
    fork: (projectId) => `/api/projects/${projectId}/fork`,
    members: (projectId) => `/api/projects/${projectId}/members`,
    memberByUserId: (projectId, userId) => `/api/projects/${projectId}/members/${userId}`,
  },
  events: {
    list: '/api/events',
    create: '/api/events/create',
    pending: '/api/events/pending',
    byId: (eventId) => `/api/events/${eventId}`,
    submit: (eventId) => `/api/events/${eventId}/submit`,
    approve: (eventId) => `/api/events/${eventId}/approve`,
    reject: (eventId) => `/api/events/${eventId}/reject`,
    cancel: (eventId) => `/api/events/${eventId}/cancel`,
    complete: (eventId) => `/api/events/${eventId}/complete`,
    register: (eventId) => `/api/events/${eventId}/register`,
    confirmAttendance: (eventId) => `/api/events/${eventId}/confirm-attendance`,
    drop: (eventId) => `/api/events/${eventId}/drop`,
    participants: (eventId) => `/api/events/${eventId}/participants`,
    tasks: (eventId) => `/api/events/${eventId}/tasks`,
    taskSubmitAction: (taskId) => `/api/events/tasks/${taskId}/submit-action`,
    taskSummary: (taskId) => `/api/events/tasks/${taskId}/summary`,
  },
  communities: {
    explore: '/api/communities/explore',
    create: '/api/communities/create',
    byId: (communityId) => `/api/communities/view/${communityId}`,
    join: (communityId) => `/api/communities/join/${communityId}`,
    message: (communityId) => `/api/communities/message/${communityId}`,
    tasks: (communityId) => `/api/communities/${communityId}/tasks`,
    createTask: (communityId) => `/api/communities/${communityId}/tasks/create`,
  },
  personnel: {
    dashboard: '/api/personnel/dashboard',
    students: '/api/personnel/students',
    whitelist: '/api/personnel/whitelist',
    whitelistAddSingle: '/api/personnel/whitelist/add-single',
    whitelistBulkAdd: '/api/personnel/whitelist/bulk-add',
    whitelistRemove: (emailId) => `/api/personnel/whitelist/remove/${emailId}`,
    profile: '/api/personnel/profile',
    emailConfig: '/api/personnel/college/email-config',
  },
  admin: {
    userStats: (userId) => `/api/admin/user-stats/${userId}`,
    penalty: (userId) => `/api/admin/penalty/${userId}`,
    bonus: (userId) => `/api/admin/bonus/${userId}`,
    skillXp: (userId) => `/api/admin/skill-xp/${userId}`,
    bulkBonus: '/api/admin/bulk-bonus',
  },
}
