"""add_event_dual_identity_fks

Revision ID: 0797b04af0db
Revises: db67220b1b6b
Create Date: 2026-02-20 15:53:48.315220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0797b04af0db'
down_revision = 'db67220b1b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_personnel_id', sa.Integer(), nullable=True))
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_events_created_by_personnel_id', 'college_personnel', ['created_by_personnel_id'], ['id'])
        batch_op.create_foreign_key('fk_events_created_by_user_id', 'users', ['created_by_user_id'], ['id'])

    # Backfill: for non-college events, copy created_by → created_by_user_id
    op.execute(
        "UPDATE events SET created_by_user_id = created_by "
        "WHERE creator_type != 'college' AND created_by IS NOT NULL"
    )

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_events_created_by_personnel_id', type_='foreignkey')
        batch_op.drop_constraint('fk_events_created_by_user_id', type_='foreignkey')
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_by_personnel_id')
        batch_op.drop_column('created_by_user_id')
