"""Add scoring history and language proficiency

Revision ID: 176c545bc015
Revises: 605332d6dad9
Create Date: 2026-02-04 23:06:59.637625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176c545bc015'
down_revision = '605332d6dad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scoring_history', schema=None) as batch_op:
        batch_op.create_index('idx_event_type', ['event_type'], unique=False)
        batch_op.create_index('idx_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('user_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('language_level', sa.Integer(), nullable=False),
    sa.Column('language_xp', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language', name='uix_user_language')
    )
    op.create_table('user_scorings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('motivation_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('dominant_roles', sa.JSON(), nullable=False),
    sa.Column('interest_scores', sa.JSON(), nullable=False),
    sa.Column('raw_role_scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # User table already exists in base migrations; no changes needed here.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_scorings')
    op.drop_table('user_languages')
    with op.batch_alter_table('scoring_history', schema=None) as batch_op:
        batch_op.drop_index('idx_user_created')
        batch_op.drop_index('idx_event_type')

    op.drop_table('scoring_history')
    # ### end Alembic commands ###
