"""Add questionnaire completion flag in user

Revision ID: 586fc7775ccb
Revises: 176c545bc015
Create Date: 2026-02-04 23:41:19.674903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586fc7775ccb'
down_revision = '176c545bc015'
branch_labels = None
depends_on = None


def upgrade():
    # 1️⃣ Add column WITH server default
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(
            sa.Column(
                'has_completed_questionnaire',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false()
            )
        )

    # 2️⃣ Backfill existing rows explicitly (extra safety)
    op.execute(
        "UPDATE users SET has_completed_questionnaire = FALSE "
        "WHERE has_completed_questionnaire IS NULL"
    )

    # 3️⃣ Remove server default (optional but recommended)
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column(
            'has_completed_questionnaire',
            server_default=None
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_completed_questionnaire')

    # ### end Alembic commands ###
