"""Add gamification fields to User model

Revision ID: 7e1ed7123058
Revises: b1080a66c1e3
Create Date: 2026-02-09 20:06:14.233134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1ed7123058'
down_revision = 'b1080a66c1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_name', name='uix_user_skill')
    )
    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.create_index('idx_user_skills', ['user_id', 'skill_name'], unique=False)

    op.create_table('xp_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('xp_transactions', schema=None) as batch_op:
        batch_op.create_index('idx_source', ['source'], unique=False)
        batch_op.create_index('idx_xp_transactions_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registration_status', sa.String(length=20), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uix_user_event_participant')
    )
    op.create_table('event_tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('selected_options', sa.JSON(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['community_polls.poll_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'poll_id', name='uix_user_poll_vote')
    )
    op.create_table('task_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('completed_actions', sa.JSON(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_action_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['community_tasks.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_id', name='uix_user_task_completion')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reputation', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('daily_xp_earned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_xp_reset_date', sa.Date(), nullable=True))
    
    # Set default values for all existing rows
    op.execute("UPDATE users SET xp = 0 WHERE xp IS NULL")
    op.execute("UPDATE users SET level = 1 WHERE level IS NULL")
    op.execute("UPDATE users SET reputation = 0 WHERE reputation IS NULL")
    op.execute("UPDATE users SET current_streak = 0 WHERE current_streak IS NULL")
    op.execute("UPDATE users SET max_streak = 0 WHERE max_streak IS NULL")
    op.execute("UPDATE users SET daily_xp_earned = 0 WHERE daily_xp_earned IS NULL")

    # Now alter columns to NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('xp', nullable=False)
        batch_op.alter_column('level', nullable=False)
        batch_op.alter_column('reputation', nullable=False)
        batch_op.alter_column('current_streak', nullable=False)
        batch_op.alter_column('max_streak', nullable=False)
        batch_op.alter_column('daily_xp_earned', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_xp_reset_date')
        batch_op.drop_column('daily_xp_earned')
        batch_op.drop_column('last_login_date')
        batch_op.drop_column('max_streak')
        batch_op.drop_column('current_streak')
        batch_op.drop_column('reputation')
        batch_op.drop_column('level')
        batch_op.drop_column('xp')

    op.drop_table('task_completions')
    op.drop_table('poll_votes')
    op.drop_table('event_tasks')
    op.drop_table('event_participants')
    with op.batch_alter_table('xp_transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_xp_transactions_user_created')
        batch_op.drop_index('idx_source')

    op.drop_table('xp_transactions')
    with op.batch_alter_table('user_skills', schema=None) as batch_op:
        batch_op.drop_index('idx_user_skills')

    op.drop_table('user_skills')
    # ### end Alembic commands ###
