"""Increase password_hash length

Revision ID: 95178afcfb8a
Revises: a9ee1e75fad1
Create Date: 2026-01-27 18:13:05.982220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95178afcfb8a'
down_revision = 'a9ee1e75fad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
