"""enhanced auth system

Revision ID: 9b69ae95562e
Revises: 7e1ed7123058
Create Date: 2026-02-10 02:11:12.189732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b69ae95562e'
down_revision = '7e1ed7123058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('personnel_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_manage_students', sa.Boolean(), nullable=False),
    sa.Column('can_manage_personnel', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'hod', 'faculty', 'staff', 'assistant', 'coordinator')", name='valid_role'),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_personnel_college', 'college_personnel', ['college_id'])
    op.create_index('idx_personnel_email', 'college_personnel', ['email'])
    op.create_index('idx_personnel_role', 'college_personnel', ['role'])
    op.create_table('whitelisted_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('student_enrollment', sa.String(length=100), nullable=True),
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('added_by_personnel_id', sa.Integer(), nullable=True),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('registered_user_id', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_personnel_id'], ['college_personnel.id'], ),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['registered_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_whitelist_college', 'whitelisted_emails', ['college_id'])
    op.create_index('idx_whitelist_email', 'whitelisted_emails', ['email'])
    op.create_index('idx_whitelist_registered', 'whitelisted_emails', ['is_registered'])
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('domain', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('student_email_pattern', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('personnel_email_pattern', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('registration_number', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['registration_number'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False, server_default=''))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('registration_number')
        batch_op.drop_column('personnel_email_pattern')
        batch_op.drop_column('student_email_pattern')
        batch_op.drop_column('domain')
        batch_op.drop_column('address')

    op.drop_index('idx_whitelist_registered', table_name='whitelisted_emails')
    op.drop_index('idx_whitelist_email', table_name='whitelisted_emails')
    op.drop_index('idx_whitelist_college', table_name='whitelisted_emails')
    op.drop_table('whitelisted_emails')
    
    op.drop_index('idx_personnel_role', table_name='college_personnel')
    op.drop_index('idx_personnel_email', table_name='college_personnel')
    op.drop_index('idx_personnel_college', table_name='college_personnel')
    op.drop_table('college_personnel')
    # ### end Alembic commands ###
