"""add city and state to colleges

Revision ID: 9dddde00badc
Revises: 57edbf52e693
Create Date: 2026-02-04 14:20:36.460436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dddde00badc'
down_revision = '57edbf52e693'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('city', sa.String(length=100), nullable=True)
        )
        batch_op.add_column(
            sa.Column('state', sa.String(length=100), nullable=True)
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
