"""Make college_id nullable

Revision ID: d99e36a6d0e5
Revises: 95178afcfb8a
Create Date: 2026-01-27 18:37:08.405098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99e36a6d0e5'
down_revision = '95178afcfb8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('college_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('college_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
